// Code generated by godddx, DO AVOID EDIT.
package sms

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// MediaServerStorer 流媒体服务器实体持久化接口
type MediaServerStorer interface {
	WithTx(orm.Tx) (MediaServerStorer, error)
	Create(context.Context, *MediaServer) error
	Update(context.Context, *MediaServer, func(*MediaServer) error) error
	Delete(context.Context, *MediaServer) error
	List(context.Context, *FindMediaServerInput) ([]*MediaServer, int64, error)
	GetByID(context.Context, string) (*MediaServer, error)
}

// ListMediaServers 分页查询
func (c Core) ListMediaServers(ctx context.Context, in *FindMediaServerInput) ([]*MediaServer, int64, error) {
	items, total, err := c.storer.MediaServer().List(ctx, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}

	for _, item := range items {
		value, ok := c.cacheServers.Load(item.ID)
		if ok {
			item.Status = value.IsOnline
		}
	}
	if items == nil {
		items = []*MediaServer{}
	}
	return items, total, nil
}

// GetMediaServer 按 ID 查询
func (c Core) GetMediaServer(ctx context.Context, id string) (*MediaServer, error) {
	out, err := c.storer.MediaServer().GetByID(ctx, id)
	if err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return out, nil
}

// CreateMediaServer 创建流媒体服务器
func (c Core) CreateMediaServer(ctx context.Context, in *AddMediaServerInput) (*MediaServer, error) {
	var out MediaServer
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	if err := c.storer.MediaServer().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateMediaServer 更新流媒体服务器
func (c Core) UpdateMediaServer(ctx context.Context, in *EditMediaServerInput, id string, serverPort int) (*MediaServer, error) {
	out := MediaServer{ID: id}
	if err := c.storer.MediaServer().Update(ctx, &out, func(b *MediaServer) error {
		return copier.Copy(b, in)
	}); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	c.connection(&out, serverPort)
	return &out, nil
}

// DeleteMediaServer 删除流媒体服务器
func (c Core) DeleteMediaServer(ctx context.Context, id string) (*MediaServer, error) {
	out := MediaServer{ID: id}
	if err := c.storer.MediaServer().Delete(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}
	return &out, nil
}

// GetDefaultMediaServer 获取默认流媒体服务器
func (c Core) GetDefaultMediaServer() (*MediaServer, error) {
	return c.storer.MediaServer().GetByID(context.Background(), DefaultMediaServerID)
}
