// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/jinzhu/copier"
)

// DeviceStorer Instantiation interface
type DeviceStorer interface {
	WithTx(orm.Tx) (DeviceStorer, error)
	Create(context.Context, *Device) error
	Update(context.Context, *Device, func(*Device) error) error
	Delete(context.Context, *Device) error
	List(context.Context, *FindDeviceInput) ([]*Device, int64, error)
	GetByID(ctx context.Context, id string) (*Device, error)
	GetByDeviceID(ctx context.Context, deviceID string) (*Device, error)
}

func (c Core) ListChannelsForDevice(ctx context.Context, in *FindDeviceInput) ([]*Device, int64, error) {
	items, total, err := c.store.Device().List(ctx, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}

	for _, item := range items {
		const size = 5
		childInput := &FindChannelInput{
			Size:    size,
			DID:     item.ID,
			Key:     in.Key,
			OrderBy: "created_at ASC",
		}
		children, _, err := c.store.Channel().List(ctx, childInput)
		if err != nil {
			continue
		}
		item.Children = children

		for _, ch := range item.Children {
			if !item.IsOnline {
				ch.IsOnline = false
				ch.IsPlaying = false
			}
		}
	}

	if items == nil {
		items = []*Device{}
	}
	return items, total, nil
}

// ListDevices Paginated search
func (c Core) ListDevices(ctx context.Context, in *FindDeviceInput) ([]*Device, int64, error) {
	items, total, err := c.store.Device().List(ctx, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}
	if items == nil {
		items = []*Device{}
	}
	return items, total, nil
}

// GetDevice Query a single object
func (c Core) GetDevice(ctx context.Context, id string) (*Device, error) {
	out, err := c.store.Device().GetByID(ctx, id)
	if err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s] id[%s]`, err.Error(), id)
		}
		return nil, reason.ErrDB.Withf(`Get err[%s] id[%s]`, err.Error(), id)
	}
	return out, nil
}

func (c Core) GetDeviceByDeviceID(ctx context.Context, deviceID string) (*Device, error) {
	out, err := c.store.Device().GetByDeviceID(ctx, deviceID)
	if err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return out, nil
}

// CreateDevice Insert into database
func (c Core) CreateDevice(ctx context.Context, in *AddDeviceInput) (*Device, error) {
	var out Device
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	// 协议验证（通过接口调用）
	if protocol, ok := c.protocols[out.GetType()]; ok {
		if err := protocol.ValidateDevice(ctx, &out); err != nil {
			return nil, reason.ErrBadRequest.WithMsg(err.Error())
		}
	}

	out.ID = GenerateDID(&out, c.uniqueID)
	if out.IsOnvif() {
		out.DeviceID = out.ID
	} else {
		out.Username = out.DeviceID
	}

	if err := out.Check(); err != nil {
		return nil, reason.ErrBadRequest.WithMsg(err.Error())
	}

	// 持久化到数据库
	if err := c.store.Device().Create(ctx, &out); err != nil {
		if orm.IsDuplicatedKey(err) {
			return nil, reason.ErrDB.WithMsg("国标 ID 重复，请勿重复添加")
		}
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}

	// 初始化协议连接（失败不影响设备添加）
	if protocol, ok := c.protocols[out.GetType()]; ok {
		if err := protocol.InitDevice(ctx, &out); err != nil {
			return nil, reason.ErrBadRequest.WithMsg(err.Error())
		}
	}

	return &out, nil
}

// UpdateDevice Update object information
func (c Core) UpdateDevice(ctx context.Context, in *EditDeviceInput, id string) (*Device, error) {
	out := Device{ID: id}
	if err := c.store.Device().Update(ctx, &out, func(b *Device) error {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}

		protocol, ok := c.protocols[out.GetType()]
		if ok {
			if err := protocol.ValidateDevice(ctx, &out); err != nil {
				slog.WarnContext(ctx, "验证协议失败", "err", err, "device_id", out.ID)
				return err
			}
		}

		return nil
	}); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s] id[%s]`, err.Error(), id)
	}

	protocol, ok := c.protocols[out.GetType()]
	if ok {
		if err := protocol.InitDevice(ctx, &out); err != nil {
			slog.WarnContext(ctx, "初始化协议失败", "err", err, "device_id", out.ID)
		}
	}
	return &out, nil
}

// DeleteDevice Delete object
// 删除设备时同步删除其下所有通道，并清理关联快照。
func (c Core) DeleteDevice(ctx context.Context, id string) (*Device, error) {
	dev, err := c.store.Device().GetByID(ctx, id)
	if err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}

	// 收集通道 ID 用于快照清理
	var channelIDs []string
	if c.coverManager != nil {
		channels, _, err := c.store.Channel().List(ctx, &FindChannelInput{
			PagerFilter: web.NewPagerFilterMaxSize(),
			DID:         id,
		})
		if err != nil {
			// 查询失败时快照清理降级为跳过，不阻断设备删除，但必须留痕以便排查快照残留
			slog.ErrorContext(ctx, "收集设备通道ID失败，跳过快照清理", "err", err, "device_id", id)
		}
		for _, ch := range channels {
			channelIDs = append(channelIDs, ch.ID)
		}
	}

	// 事务：删除设备 + 删除通道 + 协议清理
	tx, err := c.store.Begin()
	if err != nil {
		return nil, reason.ErrDB.Withf(`Begin err[%s]`, err.Error())
	}
	defer tx.Rollback()

	txDevice, err := c.store.Device().WithTx(tx)
	if err != nil {
		return nil, reason.ErrDB.Withf(`Device WithTx err[%s]`, err.Error())
	}
	txChannel, err := c.store.Channel().WithTx(tx)
	if err != nil {
		return nil, reason.ErrDB.Withf(`Channel WithTx err[%s]`, err.Error())
	}

	if err := txDevice.Delete(ctx, dev); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}

	if protocol, ok := c.protocols[dev.GetType()]; ok {
		if err := protocol.DeleteDevice(ctx, dev); err != nil {
			return nil, reason.ErrDB.Withf(`DeleteDevice err[%s]`, err.Error())
		}
	}

	if err := txChannel.DeleteByDID(ctx, id); err != nil {
		return nil, reason.ErrDB.Withf(`DeleteChannel err[%s]`, err.Error())
	}

	if err := tx.Commit(); err != nil {
		return nil, reason.ErrDB.Withf(`Commit err[%s]`, err.Error())
	}

	// 异步清理快照
	if c.coverManager != nil && len(channelIDs) > 0 {
		go func() {
			for _, cid := range channelIDs {
				if err := c.coverManager.Remove(cid); err != nil {
					slog.ErrorContext(ctx, "清理通道快照失败", "err", err, "channel_id", cid)
				}
			}
		}()
	}
	return dev, nil
}

func (c Core) QueryCatalog(ctx context.Context, deviceID string) error {
	device, err := c.GetDevice(ctx, deviceID)
	if err != nil {
		return err
	}
	if err := c.protocols[device.GetType()].QueryCatalog(ctx, device); err != nil {
		return reason.ErrBadRequest.WithMsg(err.Error())
	}
	return nil
}
