// Code generated by godddx, DO AVOID EDIT.
package config

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// ConfigStorer 配置实体持久化接口
type ConfigStorer interface {
	WithTx(orm.Tx) (ConfigStorer, error)
	Create(context.Context, *Config) error
	Update(context.Context, *Config, func(*Config) error) error
	Delete(context.Context, *Config) error
	List(context.Context, *FindConfigInput) ([]*Config, int64, error)
	GetByID(context.Context, string) (*Config, error)
	FirstOrCreate(*Config) error
}

// ListConfigs 分页查询
func (c Core) ListConfigs(ctx context.Context, in *FindConfigInput) ([]*Config, int64, error) {
	items, total, err := c.store.Config().List(ctx, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}
	if items == nil {
		items = []*Config{}
	}
	return items, total, nil
}

// GetConfig 按 ID 查询
func (c Core) GetConfig(ctx context.Context, id string) (*Config, error) {
	out, err := c.store.Config().GetByID(ctx, id)
	if err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return out, nil
}

// CreateConfig 创建配置
func (c Core) CreateConfig(ctx context.Context, in *AddConfigInput) (*Config, error) {
	var out Config
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	if err := c.store.Config().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateConfig 更新配置
func (c Core) UpdateConfig(ctx context.Context, in *EditConfigInput, id string) (*Config, error) {
	out := Config{ID: id}
	if err := c.store.Config().Update(ctx, &out, func(b *Config) error {
		return copier.Copy(b, in)
	}); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	return &out, nil
}

// DeleteConfig 删除配置
func (c Core) DeleteConfig(ctx context.Context, id string) (*Config, error) {
	out := Config{ID: id}
	if err := c.store.Config().Delete(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}
	return &out, nil
}
